// Entry point for basic-auth library
// This file exports modules for use in testing and applications

// Domain layer
pub mod domain {
    // Entities
    pub mod entities {
        pub mod user;
    }

    // Value objects
    pub mod value_objects {
        pub mod email;
    }

    // Repositories (interfaces)
    pub mod repositories {
        pub mod user_repository;
    }

    // Domain services
    pub mod services {
        pub mod authentication_service;
        pub mod user_service;
    }

    // Domain errors
    pub mod errors {
        pub mod domain_error;
    }

    // Aggregates
    // pub mod aggregates;
}

// Application layer
pub mod application {
    // DTOs
    pub mod dtos {
        pub mod auth_dto;
    }

    // Use cases
    pub mod use_cases {
        // Auth use cases
        pub mod auth {
            pub mod login_use_case;
        }

        // User use cases
        pub mod user {
            pub mod create_user_use_case;
        }
    }

    // Ports (interfaces to infrastructure)
    pub mod ports {
        pub mod token_port;
    }

    // Application services
    // pub mod services;
}

// Infrastructure layer
pub mod infrastructure {
    // Config
    pub mod config;

    // Persistence
    pub mod persistence {
        // Database models
        pub mod models {
            pub mod user_model;
        }


        // Repository implementations
        pub mod repositories {
            pub mod user_repository_impl;
        }
        pub mod schema;

        // Re-export schema
    }

    // Security implementations
    pub mod security {
        pub mod password_hasher;
        pub mod jwt_provider;
    }

    // External services
    // pub mod external_services;
}

// Interface layer
pub mod interfaces {
    // API
    pub mod api {
        // Controllers
        pub mod controllers {
            pub mod auth_controller;
            pub mod user_controller;
        }

        pub mod models {
            pub mod response;
        }
        // Middlewares
        pub mod middlewares {
            pub mod auth_middleware;
        }

        // Routes
        pub mod routes;
    }

    // CLI
    // pub mod cli;
}

// Common utilities
pub mod common {
    // Error handling
    pub mod errors;

    // Logging
    pub mod logging;

    // Utilities
    pub mod utils;

    // Models
    pub mod models {
        pub mod response;
    }
}

// Re-export schema generated by diesel
pub use infrastructure::persistence::schema;
